# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GraphqlController`.
# Please instead update this file by running `bin/tapioca dsl GraphqlController`.


class GraphqlController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
