# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::JournalEntrySortInput`.
# Please instead update this file by running `bin/tapioca dsl Types::JournalEntrySortInput`.


class Types::JournalEntrySortInput
  sig { returns(T.nilable(::Symbol)) }
  def month; end

  sig { returns(T.nilable(::Symbol)) }
  def year; end
end
